export enum TICKER_TYPE {
  'INDICATOR' = 'INDICATOR',
  'BOT' = 'BOT',
  'SYSTEM' = 'SYSTEM',
}

export enum TICKER_EVENT_TYPE {
  START = 'START',
  STOP = 'STOP',
  TRADE = 'TRADE',
  WATCHER_START = 'WATCHER_START',
  WATCHER_STOP = 'WATCHER_STOP',
  WATCHER_TRIGGERED = 'WATCHER_TRIGGERED',
  TREND_UP = 'TREND_UP',
  TREND_DOWN = 'TREND_DOWN',
}